"""initial schema

Revision ID: 17384dfab4bd
Revises:
Create Date: 2026-08-18 17:36:20.730116

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "17384dfab4bd"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "role",
        sa.Column("name", sa.String(length=45), nullable=False),
        sa.Column("privilege_level", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_role_id"), "role", ["id"], unique=True)
    op.create_index(op.f("ix_role_name"), "role", ["name"], unique=False)
    op.create_table(
        "user",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_user_id"), "user", ["id"], unique=True)
    op.create_table(
        "vector_index_meta",
        sa.Column("embedding_model", sa.String(length=255), nullable=False),
        sa.Column("embedding_dim", sa.Integer(), nullable=False),
        sa.Column("normalized", sa.Boolean(), nullable=False),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_vector_index_meta_id"), "vector_index_meta", ["id"], unique=True)
    op.create_table(
        "file_metadata",
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("content_type", sa.String(length=255), nullable=False),
        sa.Column("head_value", sa.String(length=128), nullable=True),
        sa.Column("creation_date", sa.Date(), nullable=True),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column("index_status", sa.String(length=16), nullable=False),
        sa.Column("index_error", sa.Text(), nullable=True),
        sa.Column("indexed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_file_metadata_id"), "file_metadata", ["id"], unique=True)
    op.create_index(
        op.f("ix_file_metadata_index_status"), "file_metadata", ["index_status"], unique=False
    )
    op.create_index(
        op.f("ix_file_metadata_project_id"), "file_metadata", ["project_id"], unique=False
    )
    op.create_index(
        op.f("ix_file_metadata_user_id"), "file_metadata", ["user_id"], unique=False
    )
    op.create_table(
        "local_connection",
        sa.Column("user_id", sa.String(length=36), nullable=True),
        sa.Column("name", sa.String(length=75), nullable=False),
        sa.Column("email", sa.String(length=120), nullable=False),
        sa.Column("password_hash", sa.String(length=128), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_local_connection_email"), "local_connection", ["email"], unique=True
    )
    op.create_index(op.f("ix_local_connection_id"), "local_connection", ["id"], unique=True)
    op.create_table(
        "project",
        sa.Column("title", sa.String(length=45), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_project_id"), "project", ["id"], unique=True)
    op.create_index(op.f("ix_project_user_id"), "project", ["user_id"], unique=False)
    op.create_table(
        "role_has_user",
        sa.Column("role_id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["role_id"],
            ["role.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("role_id", "user_id", "id"),
    )
    op.create_index(op.f("ix_role_has_user_id"), "role_has_user", ["id"], unique=True)
    op.create_table(
        "chunk_vector",
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("chunk_index", sa.Integer(), nullable=False),
        sa.Column("token_count", sa.Integer(), nullable=False),
        sa.Column("file_content_offset", sa.Integer(), nullable=False),
        sa.Column("file_content_length", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["file_metadata.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_chunk_vector_file_id"), "chunk_vector", ["file_id"], unique=False)
    op.create_index(op.f("ix_chunk_vector_id"), "chunk_vector", ["id"], unique=True)
    op.create_table(
        "file_has_project",
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("project_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["file_metadata.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["project_id"], ["project.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id", "project_id", "id"),
    )
    op.create_index(op.f("ix_file_has_project_id"), "file_has_project", ["id"], unique=True)
    op.create_table(
        "thread",
        sa.Column("title", sa.String(length=90), nullable=True),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("stared", sa.SmallInteger(), nullable=True),
        sa.Column("in_project", sa.SmallInteger(), nullable=True),
        sa.Column("project_id", sa.String(length=36), nullable=True),
        sa.Column(
            "creation_date", sa.Date(), server_default=sa.text("(CURRENT_DATE)"), nullable=False
        ),
        sa.Column("update_time", sa.TIMESTAMP(timezone=True), nullable=True),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["project_id"],
            ["project.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_thread_id"), "thread", ["id"], unique=True)
    op.create_index(op.f("ix_thread_project_id"), "thread", ["project_id"], unique=False)
    op.create_index(op.f("ix_thread_user_id"), "thread", ["user_id"], unique=False)
    op.create_table(
        "file_has_thread",
        sa.Column("file_id", sa.String(length=36), nullable=False),
        sa.Column("thread_id", sa.String(length=36), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(["file_id"], ["file_metadata.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["thread_id"], ["thread.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("file_id", "thread_id", "id"),
    )
    op.create_index(op.f("ix_file_has_thread_id"), "file_has_thread", ["id"], unique=True)
    op.create_table(
        "message",
        sa.Column("hash", sa.String(length=64), nullable=False),
        sa.Column("inline_value", sa.Text(), nullable=True),
        sa.Column("role", sa.String(length=30), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("thread_id", sa.String(length=36), nullable=False),
        sa.Column("order", sa.Integer(), nullable=False),
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.ForeignKeyConstraint(
            ["thread_id"],
            ["thread.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["user.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_message_hash"), "message", ["hash"], unique=False)
    op.create_index(op.f("ix_message_id"), "message", ["id"], unique=True)
    op.create_index(op.f("ix_message_thread_id"), "message", ["thread_id"], unique=False)
    op.create_index(op.f("ix_message_user_id"), "message", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_message_user_id"), table_name="message")
    op.drop_index(op.f("ix_message_thread_id"), table_name="message")
    op.drop_index(op.f("ix_message_id"), table_name="message")
    op.drop_index(op.f("ix_message_hash"), table_name="message")
    op.drop_table("message")
    op.drop_index(op.f("ix_file_has_thread_id"), table_name="file_has_thread")
    op.drop_table("file_has_thread")
    op.drop_index(op.f("ix_thread_user_id"), table_name="thread")
    op.drop_index(op.f("ix_thread_project_id"), table_name="thread")
    op.drop_index(op.f("ix_thread_id"), table_name="thread")
    op.drop_table("thread")
    op.drop_index(op.f("ix_file_has_project_id"), table_name="file_has_project")
    op.drop_table("file_has_project")
    op.drop_index(op.f("ix_chunk_vector_id"), table_name="chunk_vector")
    op.drop_index(op.f("ix_chunk_vector_file_id"), table_name="chunk_vector")
    op.drop_table("chunk_vector")
    op.drop_index(op.f("ix_role_has_user_id"), table_name="role_has_user")
    op.drop_table("role_has_user")
    op.drop_index(op.f("ix_project_user_id"), table_name="project")
    op.drop_index(op.f("ix_project_id"), table_name="project")
    op.drop_table("project")
    op.drop_index(op.f("ix_local_connection_id"), table_name="local_connection")
    op.drop_index(op.f("ix_local_connection_email"), table_name="local_connection")
    op.drop_table("local_connection")
    op.drop_index(op.f("ix_file_metadata_user_id"), table_name="file_metadata")
    op.drop_index(op.f("ix_file_metadata_project_id"), table_name="file_metadata")
    op.drop_index(op.f("ix_file_metadata_index_status"), table_name="file_metadata")
    op.drop_index(op.f("ix_file_metadata_id"), table_name="file_metadata")
    op.drop_table("file_metadata")
    op.drop_index(op.f("ix_vector_index_meta_id"), table_name="vector_index_meta")
    op.drop_table("vector_index_meta")
    op.drop_index(op.f("ix_user_id"), table_name="user")
    op.drop_table("user")
    op.drop_index(op.f("ix_role_name"), table_name="role")
    op.drop_index(op.f("ix_role_id"), table_name="role")
    op.drop_table("role")
    # ### end Alembic commands ###
