/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AreYouSureModal: typeof import('./components/chat/AreYouSureModal.vue')['default']
    ChatAnswer: typeof import('./components/chat/ChatAnswer.vue')['default']
    LoginModal: typeof import('./components/auth/LoginModal.vue')['default']
    ModalContainer: typeof import('./components/ModalContainer.vue')['default']
    PrettyMarkdown: typeof import('./components/chat/PrettyMarkdown.vue')['default']
    PromptBar: typeof import('./components/chat/PromptBar.vue')['default']
    RegisterModal: typeof import('./components/auth/RegisterModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    UserPromptBubble: typeof import('./components/chat/UserPromptBubble.vue')['default']
  }
}
