llama:
  flash_attn: true

  4gb:
    context: 4096
    max-output: 512
    batch_size: 1024
    u_batch_size: 512
  6gb:
    context: 6144
    max-output: 768
    batch_size: 1536
    u_batch_size: 512
  8gb:
    context: 16384
    max-output: 1024
    batch_size: 2048
    u_batch_size: 1024
  12gb:
    context: 24576
    max-output: 1536
    batchsize: 3072
    u_batch_size: 1024